apiVersion: klot.io/v1
kind: KlotIOApp
metadata:
  name: chore-slack.nandy.io
spec:
  namespace: chore-slack-nandy-io
  description: Chore Slack - Nandy I/O
  manifests:
  - path: daemon/kubernetes/daemon.yaml
  requires:
  - name: people.nandy.io
    source:
      site: github.com
      repo: nandy-io/people
    integrations:
    - path: daemon/forms/person.fields.yaml
  settings:
    - name: webhook_url
      description: |
        Go to the Link below.
        Create an App with the Create App button.
        Go to Incoming Webhooks.
        Add a new Webhook, selecting channel to post to.
        Copy the Webhook URL and paste it above.
      link:
        name: Slack Apps
        url: https://api.slack.com/apps
